### ISSUE TITLE
Martlet is Blurry

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI-frontend#133]
<img width="934" alt="screen shot 2018-12-08 at 6 19 43 pm" src="https://user-images.githubusercontent.com/2529120/49691800-5fcf2d00-fb18-11e8-97c0-0acf4232861d.png">
Martlet is blurry on the email confirmation page. 

Is this an SVG or a PNG? I will investigate.

**Comment by erickzhao** [comment]
Won't fix lol
