### ISSUE TITLE
Uniformize code formatting

### ISSUE THREAD

**Issue by erickzhao** [hackmcgill/hackerAPI-frontend#187]
Reference: https://github.com/sw-yx/react-typescript-cheatsheet#prettier--tslint

Prettier ([see on GitHub](https://github.com/prettier/prettier)) is a widely-used tool to format code. I think it would be very useful to get it set up because at the moment, our code style is very disorganized. Enabling Prettier and having it hooked to VS Code on save would be a step in the right direction to make our code neater and also avoid having minor style changes in every PR.

**Comment by loreina** [comment]
@erickzhao do you have a preference for using just tslint or both tslint and eslint? There are more options in eslint that we may or may not use (not really sure here) but if we do use both, we can override settings for `.ts` and `.tsx` in the eslint config file.

checkout `feature/187-prettier` to see what I've got so far

**Comment by erickzhao** [comment]
@loreina Maybe just TSLint for now. I'm not too stringent on the exact linting style. If we need ESLint plugins we can always upgrade later.
