### ISSUE TITLE
Differentiate `:hover` and `:selected`

### ISSUE THREAD

**Issue by MaxMB15** [hackmcgill/hackerAPI-frontend#199]
Differentiate `:hover` and `:selected` in dropdown so that they don't look the same

<img width="550" alt="colorthesame" src="https://user-images.githubusercontent.com/15022344/49987265-c309f680-ff40-11e8-9ac6-09c4eca47d39.png">

**Comment by pierreTklein** [comment]
@loreina what colors should the selected vs hovered items be?

**Comment by loreina** [comment]
@pierreTklein I was thinking `grey` for selected but was going to play around with it tomorrow and PR
