### ISSUE TITLE
Cap the input fields at a max length

### ISSUE THREAD

**Issue by MaxMB15** [hackmcgill/hackerAPI-frontend#200]
Users can input infinite chars which could take up all of storage.

<img width="522" alt="screen shot 2018-12-14 at 1 42 55 am" src="https://user-images.githubusercontent.com/15022344/49987539-9acec780-ff41-11e8-8e6c-8fc19b235830.png">

**Comment by pierreTklein** [comment]
@loreina how should we display max char count

**Comment by pierreTklein** [comment]
![image](https://user-images.githubusercontent.com/17463268/49988511-f64e8480-ff44-11e8-8122-a89409afbc73.png)

**Comment by loreina** [comment]
Unbold it and unmisspell` characters` 👀 Maybe right align too?

My only thing is to make it differentiable from the question

@ailishm might have more to say about this
