### ISSUE TITLE
Database Viewing Table

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI-frontend#209]
# Feature

- Sponsors want to be able to view some parts of the hacker information. They should be able to search by different fields, such as:
  - Graduation year
  - Skills
  - University
  - Email
- Admins want to be able to view all sorts of user information, and perform bulk actions on them, such as sending emails to hackers, or change their status.

**Comment by pierreTklein** [comment]
@krubenok can you flesh out the spec for this please?

**Comment by krubenok** [comment]
LOL was literally commenting just now that I was gonna add myself to design the spec for what's needed in the table.

**Comment by krubenok** [comment]
As a starting point, we should look at designing two views, I will flesh out what is contained in those views in more detail next week but as a start here are some seeds to think about: 

- a table view that shows columns with various attributes about hackers (status, School, name, bus, etc..) with side/top bars for searching and performing bulk actions (@pierreTklein are bulk actions a thing that we are capable of rn with the api?)
- a single hacker view that shows all the details of the hacker with all of their fields. Keep in mind the design for this should permit for different levels of access where some users can't see all the fields (volunteers should only see school, email, name, status; admins see everything; sponsors only see skill and resume type stuff and email or something)

**Comment by pierreTklein** [comment]
@ailishm do you think you can start drafting something up for this?

**Comment by ailishm** [comment]
yep! just have one final tonight and then i'll get right on it

**Comment by pierreTklein** [comment]
Good luck on your final !!!
