### ISSUE TITLE
when selected, shirt size stays `white`.

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI-frontend#210]
![image](https://user-images.githubusercontent.com/23108291/49989552-91952900-ff48-11e8-898e-cc9e064052e4.png)

_Originally posted by @loreina in https://github.com/hackmcgill/hackerAPI-frontend/pull/203#issuecomment-447240295_

**Comment by erickzhao** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/16010076/50857410-8ffa2d80-135b-11e9-9620-16feb2698eb1.png">

Can't reproduce? cc @loreina 

Will close.
