### ISSUE TITLE
Fix linting script

### ISSUE THREAD

**Issue by loreina** [hackmcgill/hackerAPI-frontend#215]
@krubenok @pierreTklein @erickzhao 

I added some dependencies to make the lint script work because it wasn't working before.

Now I'm facing a separate issue:

When calling the script `npm run lint`, the build ends with an error

![image](https://user-images.githubusercontent.com/23108291/50039810-d2ec0e00-0006-11e9-8087-554b8de6910e.png)

When I just type the script into terminal `tslint 'src/**/*.{ts,tsx}'` it works fine?????

![image](https://user-images.githubusercontent.com/23108291/50039818-e13a2a00-0006-11e9-88e5-1e4bf3fff8f5.png)

Pls help me. Ideas on what to do?? Apparently this is a known bug that happens to other people but has also been fixed from time to time??? If we can live with the error, I guess that's fine 🤷‍♀️ but maybe I'm just fried and it's a me issue here

Checkout branch `lint-script` to play around with it.

`tslint 'src/**/*.{ts,tsx}'` finds the linting errors
`tslint --fix 'src/**/*.{ts,tsx}'` finds and fixes the linting errors

**Comment by krubenok** [comment]
@loreina is there a reason you are recommending the tslint plugin from Microsoft with ~20k downloads vs. the one from egamma with ~10M downloads?

https://marketplace.visualstudio.com/items?itemName=eg2.tslint

**Comment by krubenok** [comment]
I did a quick'npm install' and 'npm install -g npm' b/c I was told a minor update was available and it started working?

**Comment by krubenok** [comment]
In the branch I made for this issue I also added a `.nvmrc` file to keep node versions consistent on the project. Info on nvm here: https://github.com/creationix/nvm
